#!/bin/bash

# Fulcrum Public Gateway - Home Server Setup Script
set -e

# Get the directory of this script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Source configuration
if [ -f "$PROJECT_ROOT/config.env" ]; then
    source "$PROJECT_ROOT/config.env"
else
    echo "❌ Configuration file not found: $PROJECT_ROOT/config.env"
    echo "Please ensure config.env exists in the project root directory."
    exit 1
fi

echo "🏠 Setting up Fulcrum Public Gateway - Home Server"
echo "=================================================="

print_info "Using configuration:"
print_info "  Domain: $DOMAIN"
print_info "  Fulcrum Port: $FULCRUM_PORT"
print_info "  Service Name: $SERVICE_NAME"
print_info "  SSH Key Path: $SSH_KEY_PATH"

# Check if fulcrum is configured
print_info "Checking fulcrum configuration..."
if [ ! -f "$FULCRUM_CONFIG_PATH" ]; then
    print_error "Fulcrum config not found at $FULCRUM_CONFIG_PATH"
    print_error "Please install and configure fulcrum first."
    exit 1
fi

# Verify fulcrum is configured for the correct port
if ! grep -q "electrum_rpc_addr.*$FULCRUM_PORT" "$FULCRUM_CONFIG_PATH"; then
    print_warning "Fulcrum may not be configured for port $FULCRUM_PORT"
    print_warning "Please verify your fulcrum configuration."
fi

# Check if fulcrum is running
if ! pgrep -f fulcrum > /dev/null; then
    print_warning "Fulcrum is not currently running"
    print_warning "Please start fulcrum before continuing"
fi

# Get VPS connection details
echo ""
echo "Please provide your VPS connection details:"
echo ""

read -p "VPS hostname or IP: " VPS_HOST
read -p "VPS username (e.g., root): " VPS_USER

# Update the config file with VPS details
print_info "Saving VPS configuration..."
sed -i "s/^VPS_HOST=.*/VPS_HOST=\"$VPS_HOST\"/" "$PROJECT_ROOT/config.env"
sed -i "s/^VPS_USER=.*/VPS_USER=\"$VPS_USER\"/" "$PROJECT_ROOT/config.env"

print_info "Generating SSH keys..."
# Generate SSH key if it doesn't exist
if [ ! -f "$SSH_KEY_PATH" ]; then
    print_info "Generating new SSH key..."
    ssh-keygen -t ed25519 -f "$SSH_KEY_PATH" -N "" -C "${SSH_KEY_NAME}@$(hostname)"
    print_success "SSH key generated at $SSH_KEY_PATH"
else
    print_info "SSH key already exists at $SSH_KEY_PATH"
fi

# Copy SSH key to VPS
print_info "Installing SSH key on VPS..."
echo "You will be prompted for your VPS password:"
ssh-copy-id -i "${SSH_KEY_PATH}.pub" "${VPS_USER}@${VPS_HOST}"

# Test SSH connection
print_info "Testing SSH connection..."
if ssh -i "$SSH_KEY_PATH" -o BatchMode=yes -o ConnectTimeout=10 "${VPS_USER}@${VPS_HOST}" exit 2>/dev/null; then
    print_success "SSH key authentication working"
else
    print_error "SSH key authentication failed"
    exit 1
fi

# Create systemd service file
print_info "Creating systemd service..."
sudo tee /etc/systemd/system/${SERVICE_NAME}.service > /dev/null << SERVICEEOF
[Unit]
Description=Fulcrum SSH Tunnel to VPS
After=network.target
Wants=network.target

[Service]
Type=simple
User=$(whoami)
ExecStart=/usr/bin/ssh -i $SSH_KEY_PATH -o ServerAliveInterval=30 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -N -R $FULCRUM_PORT:localhost:$FULCRUM_PORT ${VPS_USER}@${VPS_HOST}
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
SERVICEEOF

# Reload systemd and enable service
print_info "Enabling systemd service..."
sudo systemctl daemon-reload
sudo systemctl enable ${SERVICE_NAME}.service

# Start the service
print_info "Starting tunnel service..."
sudo systemctl start ${SERVICE_NAME}.service

# Wait a moment for service to start
sleep 2

# Check service status
if sudo systemctl is-active --quiet ${SERVICE_NAME}.service; then
    print_success "Tunnel service started successfully"
else
    print_error "Tunnel service failed to start"
    print_error "Check logs with: journalctl -u ${SERVICE_NAME} -f"
    exit 1
fi

# Create configuration file for scripts
CONFIG_FILE="$PROJECT_ROOT/.fulcrum_config"
cat > "$CONFIG_FILE" << CONFIGEOF
# Fulcrum Public Gateway Runtime Configuration
# This file is generated by setup.sh

VPS_HOST="$VPS_HOST"
VPS_USER="$VPS_USER"
SSH_KEY_PATH="$SSH_KEY_PATH"
SERVICE_NAME="$SERVICE_NAME"
FULCRUM_PORT="$FULCRUM_PORT"
DOMAIN="$DOMAIN"
CONFIGEOF

print_success "Home server setup completed!"

echo ""
echo "Next steps:"
echo "1. Run the VPS setup script on your VPS server"
echo "2. Configure DNS to point $DOMAIN to your VPS IP"
echo "3. Test the connection with: ./scripts/tunnel-status.sh"
echo ""
echo "Management commands:"
echo "  ./scripts/tunnel-status.sh   - Check tunnel status"
echo "  ./scripts/tunnel-restart.sh  - Restart tunnel"
echo "  ./scripts/check-fulcrum.sh   - Check fulcrum status"

